### ISSUE TITLE
Fordelete.txt is generated in the directory after publishing

### ISSUE THREAD

**Issue by lisenz** [FlukeFan/ZipDeploy#1]
many files named "xxxx.Fordelete.txt" is generated in the directory after publishing, and The deployed.zip file is not generated

**Comment by FlukeFan** [comment]
Hi @lisenz,

The in-use files are renamed before recycling the application.  _When the application starts up again_, the files should be removed:  https://github.com/FlukeFan/ZipDeploy/blob/master/ZipDeploy/Cleaner.cs#L24

If that is not happening, can you tell me more about your setup so I can reproduce this?

Cheers

**Comment by lisenz** [comment]
Hi @FlukeFan ，
I tested my application a few more times later，the files  was indeed removed，but the deployed.zip file is still not generated.
I am using the code from the quickstart example：services.AddZipDeploy();

Thanks

**Comment by FlukeFan** [comment]
Hmm ... that is strange, because that happens before the restart.

The (obsolete) files are renamed here:  https://github.com/FlukeFan/ZipDeploy/blob/master/ZipDeploy/Unzipper.cs#L45
Then the publish.zip is renamed to deployed.zip here (2 lines below):  https://github.com/FlukeFan/ZipDeploy/blob/master/ZipDeploy/Unzipper.cs#L48

Is there any log output to suggest why it's not getting that far?  (Perhaps even in the application event logs?)

**Comment by lisenz** [comment]
@FlukeFan 
I found the generated log file with hints in it：Error during moving file wwwroot/logs/log-20220317.txt to wwwroot\logs\zzz__log-20220317.txt.fordelete.txt  System.IO.IOException: The process cannot access the file because it is being used by another process.

The following is the entire log file：
[log-20220317.txt](https://github.com/FlukeFan/ZipDeploy/files/8281100/log-20220317.txt)

**Comment by FlukeFan** [comment]
I think I see the problem.  ZipDeploy is trying to update the IIS folder to have the same files as the zip file, but in your case, you are also logging to a 'logs' folder?  (I think?)

So I suspect there are two options that might help:

1.  Don't log to the same folder as the binaries (e.g., move your logs folder out of the IIS folder);
2. Tell ZipDeploy to ignore those files:

`services.AddZipDeploy(o => o.IgnorePathStarting("wwwroot/logs"))`

Let me know if that helps.

**Comment by lisenz** [comment]
@FlukeFan 
Hi，I tried as you said and you're right.
Tell ZipDeploy to ignore the 'logs' folder: 
`services.AddZipDeploy(o => o.IgnorePathStarting("wwwroot/logs"))`，and it works.
My problem solved，thank you a lot.

**Comment by lisenz** [comment]
Hi，I tried as you said and you're right.

Tell ZipDeploy to ignore the 'logs' folder:
services.AddZipDeploy(o => o.IgnorePathStarting("wwwroot/logs"))，and it works.

My problem solved，thank you a lot.

**Comment by FlukeFan** [comment]
You're welcome, I'm glad that worked.

Just as an aside, I suspect that logging into the wwwroot folder might expose your logs files externally.  (Possibly you don't want to do that.)

**Comment by lisenz** [comment]
Yes, you're right. 

the logs folder should be move out of the IIS folder.(I will improve this later.)
