### ISSUE TITLE
Is it possible to add the function of canceling file renaming

### ISSUE THREAD

**Issue by loda7023link** [FlukeFan/ZipDeploy#3]
Sometimes, project release does not necessarily need to overwrite and update all files, such as appsettings.json, wwwroot.
And now every time you publish, as long as the files that are not in the compressed package are renamed.

![image](https://github.com/FlukeFan/ZipDeploy/assets/28056027/0bccdf3b-81d3-48e9-bbed-a9d02d6b86ac)

**Comment by FlukeFan** [comment]
So the first time the files are unzipped, a hash is created of all the files (and stored in a file named zipDeployFileHashes.txt).  After that, when unzipping, it only replaces files where the hash has changed.  So if nothing has changed in your wwwroot folder, ZipDeploy won't replace/rename/delete any of those files.

**Comment by FlukeFan** [comment]
This may also be related to the discussion here:  https://github.com/FlukeFan/ZipDeploy/issues/2

**Comment by FlukeFan** [comment]
Let me know if that doesn't answer your question.
